# Generated by Django 4.2.28 on 2026-03-17 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_visits', models.IntegerField(default=0)),
                ('new_visitors', models.IntegerField(default=0)),
                ('returning_visitors', models.IntegerField(default=0)),
                ('bot_visits', models.IntegerField(default=0)),
                ('human_visits', models.IntegerField(default=0)),
                ('countries_represented', models.IntegerField(default=0)),
                ('top_country', models.CharField(blank=True, max_length=100, null=True)),
                ('top_page', models.CharField(blank=True, max_length=500, null=True)),
                ('pages_visited', models.IntegerField(default=0)),
                ('average_session_duration', models.IntegerField(default=0)),
                ('admin_visits', models.IntegerField(default=0)),
                ('user_visits', models.IntegerField(default=0)),
                ('anonymous_visits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Visitor Analytics',
                'verbose_name_plural': 'Daily Visitor Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminIPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('description', models.CharField(blank=True, help_text="e.g., 'Office', 'Home', 'VPN'", max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin IP Whitelist',
                'verbose_name_plural': 'Admin IP Whitelists',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('page_count', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_admin_ip', models.BooleanField(default=False)),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_visit'],
                'indexes': [models.Index(fields=['ip_address', 'last_visit'], name='visitor_tra_ip_addr_0636a8_idx'), models.Index(fields=['session_id', 'last_visit'], name='visitor_tra_session_209c24_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField()),
                ('referer', models.CharField(blank=True, max_length=500, null=True)),
                ('page_visited', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(default=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_admin_ip', models.BooleanField(db_index=True, default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'is_admin_ip'], name='visitor_tra_timesta_7df97f_idx'), models.Index(fields=['page_visited', 'timestamp'], name='visitor_tra_page_vi_5c2965_idx'), models.Index(fields=['ip_address', 'timestamp'], name='visitor_tra_ip_addr_a018e1_idx'), models.Index(fields=['country', 'timestamp'], name='visitor_tra_country_7e4fc4_idx')],
            },
        ),
    ]
