# Generated by Django 4.2.28 on 2026-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text="User's preferred language for emails and AI insights", max_length=5),
        ),
    ]
