"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fy-ki7by*d-j-g+09ied7rb%o!4t(_74ko)bb(hsu&#sn^#rt@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "meditrack.up.railway.app",
    "meditrack1.up.railway.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://meditrack7.vercel.app",
    'https://meditrack.up.railway.app',
    'https://meditrack1.up.railway.app',
    "localhost",
    "127.0.0.1"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_celery_beat',
    'django_ratelimit',
    'drf_spectacular',


    'accounts',
    'medications',
    'django_filters',
    'symptoms',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

from decouple import config

import dj_database_url




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Add this line
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'MediTrack API',
    'DESCRIPTION': 'Personal Health & Medication Reminder API with AI insights',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

CORS_ALLOW_CREDENTIALS = True
# After CORS_ALLOW_CREDENTIALS and CORS_ALLOWED_ORIGINS
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://meditrack7.vercel.app",
    'https://meditrack.up.railway.app',
    'https://meditrack1.up.railway.app',
]

CSRF_TRUSTED_ORIGINS = [
    'https://meditrack.up.railway.app',
    'https://meditrack7.vercel.app',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    
]

AUTH_USER_MODEL='accounts.User'


GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

#for testing ai insights without using api tokens

USE_MOCK_AI = config('USE_MOCK_AI', default=False, cast=bool)



import os

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
USE_TZ = True




EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"



if not DEBUG:
    SECURE_SSL_REDIRECT=True
    SESSION_COOKIE_SECURE=True
    CSRF_COOKIE_SECURE=True
    SECURE_BROWSER_XSS_FILTER =True
    SECURE_CONTENT_TYPE_NOSNIFF=True
    X_FRAME_OPTIONS='DENY'
    SECURE_HSTS_SECONDS=3153600
    SECURE_HSTS_INCLUDE_SUBDOMAINS=True
    SECURE_HSTS_PRELOAD=True
 
# Unhash the below for local testing 
#DATABASES = {
 # 'default': {
  #    'ENGINE': 'django.db.backends.sqlite3',
   #   'NAME': BASE_DIR / 'db.sqlite3',
 #}
 #}


# Development: Using SQLite (switch to PostgreSQL for production) 
DATABASES = {
  'default': dj_database_url.config(
  default=os.environ.get('DATABASE_URL'),
 conn_max_age=600,
conn_health_checks=True,
)
}

#Google Oauth for direct google login 

GOOGLE_OAUTH_CLIENT_ID=config('GOOGLE_CLIENT_ID',default='')
GOOGLE_OAUTH_CLIENT_SECRET=config('GOOGLE_CLIENT_SECRET',default='')

# Google OAuth - Cross-Origin Policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = None