# fhir_integration/urls.py
"""
FHIR API URL Configuration
Maps FHIR endpoints to ViewSets
Base URL: /fhir/r4/
"""

from django.urls import path, include
from rest_framework import routers
from . import views

# Create router for FHIR ViewSets
router = routers.SimpleRouter(trailing_slash=True)

# Register FHIR resource ViewSets
router.register(r'Patient', views.FHIRPatientViewSet, basename='fhir-patient')
router.register(r'Medication', views.FHIRMedicationViewSet, basename='fhir-medication')
router.register(r'MedicationStatement', views.FHIRMedicationStatementViewSet, basename='fhir-medication-statement')
router.register(r'Observation', views.FHIRObservationViewSet, basename='fhir-observation')

app_name = 'fhir'

urlpatterns = [
    # FHIR REST endpoints (auto-generated by router)
    path('r4/', include(router.urls)),
    
    # FHIR metadata endpoint (CapabilityStatement)
    path('r4/metadata/', views.FHIRMetadataView.as_view(), name='fhir-metadata'),
    
    # SMART on FHIR configuration
    path('r4/.well-known/smart-configuration', views.SMARTConfigurationView.as_view(), name='smart-config'),
]
